config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :book_news
  resources :subjects
  resources :books
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'books#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book_new.rb
class BookNew < ApplicationRecord
  belongs_to :subject
  validates_presence_of :title, :author, :publisher
  validates_uniqueness_of :title
  validates_numericality_of :year
end

app/controllers/book_news_controller.rb
class BookNewsController < ApplicationController
  before_action :set_book_news, only: %i[ show edit update destroy ]

  # GET /book_news or /book_news.json
  def index
    @book_news = BookNew.all
  end

  # GET /book_news/1 or /book_news/1.json
  def show
  end

  # GET /book_news/new
  def new
    @book_news = BookNew.new
  end

  # GET /book_news/1/edit
  def edit
  end

  # POST /book_news or /book_news.json
  def create
    @book_news = BookNew.new(book_news_params)

    respond_to do |format|
      if @book_news.save
        format.html { redirect_to book_news_url(@book_news), notice: "Book new was successfully created." }
        format.json { render :show, status: :created, location: @book_news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_news/1 or /book_news/1.json
  def update
    respond_to do |format|
      if @book_news.update(book_news_params)
        format.html { redirect_to book_news_url(@book_news), notice: "Book new was successfully updated." }
        format.json { render :show, status: :ok, location: @book_news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_news/1 or /book_news/1.json
  def destroy
    @book_news.destroy

    respond_to do |format|
      format.html { redirect_to book_news_url, notice: "Book new was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_news
      @book_news = BookNew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_news_params
      params.require(:book_news).permit(:title, :author, :publisher, :year, :borrowed_at, :available, :subject_id)
    end
end

app/helpers/book_news_helper.rb
module BookNewsHelper
end

app/views/book_news/_book_new.html.erb
<div id="<%= dom_id book_new %>">
  <p>
    <strong>Title:</strong>
    <%= book_new.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book_new.author %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= book_new.publisher %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= book_new.year %>
  </p>

  <p>
    <strong>Borrowed at:</strong>
    <%= book_new.borrowed_at %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= book_new.available %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= book_new.subject_id %>
  </p>

</div>

app/views/book_news/_form.html.erb
<%= form_with(model: book_news) do |form| %>
<% if book_news.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(book_news.errors.count, "error") %> prohibited this book_news from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% book_news.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :title, class: label_class %>
          <%= form.text_field :title, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :author, class: label_class %>
          <%= form.text_field :author, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :publisher, class: label_class %>
          <%= form.text_field :publisher, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :year, class: label_class %>
          <%= form.number_field :year, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :borrowed_at, class: label_class %>
          <%= form.datetime_field :borrowed_at, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :available, class: label_class %>
          <%= form.check_box :available, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :subject_id, class: label_class %>
          <%= form.select :subject_id, options_from_collection_for_select(Subject.all, 'id', 'name', selected = book.subject_id), class: label_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if book_news.persisted? %>
<%= link_to "Cancel", book_news, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", book_news_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/book_news/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit book_news</h1>
    <% if @book_news.persisted? %>
    <%= button_to 'Destroy', @book_news, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', book_news: @book_news %>
</div>

app/views/book_news/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Book_news</h1>

    <%= link_to new_book_news_path, class: button_class(theme: "primary") do %>
    Add New Book new
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Title</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Author</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Publisher</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Year</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Borrowed at</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Available</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Subject</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @book_news.each do |book_news| %>
      <%= content_tag :tr, id: dom_id(book_news), class: dom_class(book_news) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book_news.title %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book_news.author %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book_news.publisher %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book_news.year %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book_news.borrowed_at %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book_news.available %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book_news.subject.name %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', book_news %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/book_news/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New book_news</h1>

  <%= render 'form', book_news: @book_news %>
</div>

app/views/book_news/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Book_news</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to book_news_path, class: button_class(theme: "transparent") do %>
      All Book_news
      <% end %>
      <%= link_to edit_book_news_path(@book_news), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Title:</p>
        <p><%= @book_news.title %></p>
      </li>
      <li>
        <p class="font-semibold">Author:</p>
        <p><%= @book_news.author %></p>
      </li>
      <li>
        <p class="font-semibold">Publisher:</p>
        <p><%= @book_news.publisher %></p>
      </li>
      <li>
        <p class="font-semibold">Year:</p>
        <p><%= @book_news.year %></p>
      </li>
      <li>
        <p class="font-semibold">Borrowed at:</p>
        <p><%= @book_news.borrowed_at %></p>
      </li>
      <li>
        <p class="font-semibold">Available:</p>
        <p><%= @book_news.available %></p>
      </li>
      <li>
        <p class="font-semibold">Subject:</p>
        <p><%= @book_news.subject %></p>
      </li>
  </ul>
</div>