config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :book_news
  resources :subjects
  resources :books
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'books#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :subject
	validates_presence_of :title, :author, :publisher
	validates_uniqueness_of :title
	validates_numericality_of :year
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:Title, :Author, :Publisher, :Year)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.Title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.Author %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= book.Publisher %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= book.Year %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
<% if book.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :Title, class: label_class %>
          <%= form.text_field :Title, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Author, class: label_class %>
          <%= form.text_field :Author, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Publisher, class: label_class %>
          <%= form.text_field :Publisher, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :Year, class: label_class %>
          <%= form.number_field :Year, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if book.persisted? %>
<%= link_to "Cancel", book, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", books_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/books/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit book</h1>
    <% if @book.persisted? %>
    <%= button_to 'Destroy', @book, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', book: @book %>
</div>

app/views/books/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Books</h1>

    <%= link_to new_book_path, class: button_class(theme: "primary") do %>
    Add New Book
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Title</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Author</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Publisher</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Year</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
      <%= content_tag :tr, id: dom_id(book), class: dom_class(book) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book.Title %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book.Author %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book.Publisher %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= book.Year %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', book %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/books/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New book</h1>

  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Book</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to books_path, class: button_class(theme: "transparent") do %>
      All Books
      <% end %>
      <%= link_to edit_book_path(@book), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Title:</p>
        <p><%= @book.Title %></p>
      </li>
      <li>
        <p class="font-semibold">Author:</p>
        <p><%= @book.Author %></p>
      </li>
      <li>
        <p class="font-semibold">Publisher:</p>
        <p><%= @book.Publisher %></p>
      </li>
      <li>
        <p class="font-semibold">Year:</p>
        <p><%= @book.Year %></p>
      </li>
  </ul>
</div>